apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rodrigo-Arcos/Prueba02.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

